Squah and Merge pull request #1 from jbw9964/ci-test-1
- 테스트 어플리케이션 추가
  - dev, test 프로필 분리
  - `@ActiveProfiles("test")` 시 test 프로필 사용
  - test 프로필 사용 시 h2 in memory 사용

- CI workflow 추가
  - gradle 빌드 시 cache 이용 : `actions/cache@v4.1.2`
  - PR 댓글에 테스트 결과 보여줌 : `EnricoMi/publish-unit-test-result-action@v2.18.0`
  - 실패한 테스트 부분에 code review 댓글 달아줌 : `mikepenz/action-junit-report@v5`

diff --git a/.github/workflows/test-ci.yml b/.github/workflows/test-ci.yml
--- a/.github/workflows/test-ci.yml
+++ b/.github/workflows/test-ci.yml
@@ -1,10 +1,10 @@
 # Workflow 이름
-name: CI with Gradle
+name: CI Report with Gradle
 
 # 트리거 이벤트
 on:
   pull_request:
-    branches: [ "main", "develop" ]
+    branches: [ "main", "master", "develop", "release" ]
 
 # 테스트 결과 작성을 위해 쓰기 권한 추가
 permissions: write-all
@@ -20,11 +20,13 @@ jobs:
       # workflow 가 repo 에 접근하기 위한 Marketplace action
       - uses: actions/checkout@v4.2.2
 
+
       - name: Set up JDK 17
         uses: actions/setup-java@v4.5.0
         with:
           java-version: '17'
           distribution: 'oracle'  # 그냥 Oracle JDK
+
 
       # gradle 캐시해서 빌드 시간 단축
       - name: Gradle caching
@@ -32,69 +34,55 @@ jobs:
         with:
           # cache 저장할 폴더 설정
           path: |
-            ~/App1/.gradle/caches
-          #            ~/App1/.gradle/wrapper
+            ~/.gradle/caches
+            ~/.gradle/wrapper
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys:
             ${{ runner.os }}-gradle-
 
-      - name: Show tree structure
-        run: |
-          echo 'App 1 : '
-          tree ~/App1
-      #          echo 'App 2 : '
-      #          tree ~/App2
 
       # gradlew 실행 권한 부여
       - name: Grant Execute Permission For Gradlew
         run: |
-          chmod +x ~/App1/gradlew
-      #          chmod +x ~/App2/gradlew
+          cd App1
+          chmod +x ./gradlew
+
 
       # test 없이 그냥 build
       - name: Build with Gradle
         run: |
-          ~/App1/gradlew build -x test
-      #          ~/App2/gradlew build -x test
+          cd App1
+          ./gradlew build -x test --build-cache
 
-      - name: Show tree structure
-        run: |
-          echo 'App 1 : '
-          tree ~/App1
-      #          echo 'App 2 : '
-      #          tree ~/App2
 
       # 테스트 실행
       - name: Run Tests
         run: |
-          ~/App1/gradlew --info test
-      #          ~/App2/gradlew --info test
+          cd App1
+          ./gradlew --info test
 
 
-      - name: Show tree structure
+      # 우리 repo 디렉토리는 ~/ 아니라 그냥 ./ 임
+      - name: Show CWD Properties
         run: |
-          echo 'App 1 : '
-          tree ~/App1
-      #          echo 'App 2 : '
-      #          tree ~/App2
+          echo "Current directory : `pwd`"
+          ls -al
+          echo 'tree ./'
+          tree ./ -a
 
-      # ??
-      - name: Publish Unit Test Results
+      # Pull Request 코멘트에 테스트 결과 댓글 달기
+      - name: Publish Unit Test Results To PR Comment
         uses: EnricoMi/publish-unit-test-result-action@v2.18.0
-        if: ${{ always() }}
+        if: ${{ always() }}   # 앞에 step 이 fail 해도 실행
         with:
-          files: ~/**/build/test-results/**/*.xml
+          files: App1/build/test-results/**/*.xml
 
-      - name: Show tree structure
-        run: |
-          echo 'App 1 : '
-          tree ~/App1
-      #          echo 'App 2 : '
-      #          tree ~/App2
 
-      # ??
-      - name: Publish Test Report
+      # 테스트 실패한 부분 PR Code Review 에 주석 달기
+      - name: Add Failed Test Annotation to PR Code Review
         uses: mikepenz/action-junit-report@v5
-        if: success() || failure()
+        if: success() || failure()  # 앞에 step 이 fail 해도 실행
         with:
-          report_paths: '**/build/test-results/test/Test-*.xml'
+          # test report 위치
+          report_paths: '**/build/test-results/test/*.xml'
+          require_tests: true
